/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is autogenerated

package com.android.car.sensitiveapplock.metrics;


import android.os.Build;
import android.util.StatsEvent;
import android.util.StatsLog;
import androidx.annotation.RequiresApi;


/**
 * Utility class for logging statistics events.
 *
 * Reflection is used here because car-sensitiveapplock-app needs gradle support and Stats* classes
 * are SystemApis which cannot be accessed via gradle. The write method was initially generated
 * using the genrule: genrule { name: "statslog-sensitiveapplock-java-gen",
 * tools: ["stats-log-api-gen"], cmd: "$(location stats-log-api-gen) --java $(out)
 * --module sensitiveapplock + " --javaPackage  com.android.car.sensitiveapplock.metrics" +
 * " --javaClass SensitiveAppLockStatsLog --minApiLevel 34", out:
 * ["com/android/car/sensitiveapplock/metrics/SensitiveAppLockStatsLog.java"], }
 *
 * @hide
 */
public final class SensitiveAppLockStatsLog {
    // Constants for atom codes.

    /**
     * SensitiveAppLockStateChanged sensitive_app_lock_state_changed<br>
     * Usage: StatsLog.write(StatsLog.SENSITIVE_APP_LOCK_STATE_CHANGED, boolean app_lock_enabled, int[] packages_uid, boolean profile_lock_enabled);<br>
     */
    public static final int SENSITIVE_APP_LOCK_STATE_CHANGED = 1030;

    /**
     * SensitiveAppLockEventReported sensitive_app_lock_event_reported<br>
     * Usage: StatsLog.write(StatsLog.SENSITIVE_APP_LOCK_EVENT_REPORTED, int package_uid, int event_type, int sign_in_event_type, int recovery_flow_event_type);<br>
     */
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED = 1172;

    // Constants for enum values.

    // Values for SensitiveAppLockEventReported.event_type
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__UNSPECIFIED_APP_LOCK_EVENT_TYPE = 0;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__APP_LOCK_ENABLED = 1;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__APP_LOCK_DISABLED = 2;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__APP_LOCK_SETTINGS_SCREEN_OPENED = 3;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__PACKAGED_ADDED = 4;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__PACKAGE_REMOVED = 5;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__PACKAGE_UNLOCK_REQUESTED = 6;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__PACKAGE_LAUNCHED = 7;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__DISCOVERY_NOTIFICATION_SHOWN = 8;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__DISCOVERY_NOTIFICATION_CLICKED = 9;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__DISCOVERY_NOTIFICATION_DISMISSED = 10;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__EVENT_TYPE__DISCOVERY_NOTIFICATION_PERMANENTLY_DISMISSED = 11;

    // Values for SensitiveAppLockEventReported.sign_in_event_type
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__SIGN_IN_EVENT_TYPE__UNSPECIFIED_SIGN_IN_EVENT_TYPE = 0;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__SIGN_IN_EVENT_TYPE__USER_ALREADY_SIGNED_IN = 1;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__SIGN_IN_EVENT_TYPE__USER_STARTED_SIGN_IN = 2;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__SIGN_IN_EVENT_TYPE__USER_COMPLETED_SIGN_IN = 3;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__SIGN_IN_EVENT_TYPE__USER_DECLINED_SIGN_IN = 4;

    // Values for SensitiveAppLockEventReported.recovery_flow_event_type
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__RECOVERY_FLOW_EVENT_TYPE__UNSPECIFIED_RECOVERY_FLOW_EVENT_TYPE = 0;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__RECOVERY_FLOW_EVENT_TYPE__USER_STARTED_REAUTH_RECOVERY_FLOW = 1;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__RECOVERY_FLOW_EVENT_TYPE__USER_COMPLETED_REAUTH_RECOVERY_FLOW = 2;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__RECOVERY_FLOW_EVENT_TYPE__USER_STARTED_MANUAL_RESET_RECOVERY_FLOW = 3;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__RECOVERY_FLOW_EVENT_TYPE__USER_STARTED_PIN_RECREATE_FLOW = 4;
    public static final int SENSITIVE_APP_LOCK_EVENT_REPORTED__RECOVERY_FLOW_EVENT_TYPE__USER_RECREATED_PIN = 5;

    // Annotation constants.
    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_IS_UID = StatsLog.ANNOTATION_ID_IS_UID;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_TRUNCATE_TIMESTAMP = StatsLog.ANNOTATION_ID_TRUNCATE_TIMESTAMP;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_PRIMARY_FIELD = StatsLog.ANNOTATION_ID_PRIMARY_FIELD;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_EXCLUSIVE_STATE = StatsLog.ANNOTATION_ID_EXCLUSIVE_STATE;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_PRIMARY_FIELD_FIRST_UID = StatsLog.ANNOTATION_ID_PRIMARY_FIELD_FIRST_UID;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_DEFAULT_STATE = StatsLog.ANNOTATION_ID_DEFAULT_STATE;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_TRIGGER_STATE_RESET = StatsLog.ANNOTATION_ID_TRIGGER_STATE_RESET;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_STATE_NESTED = StatsLog.ANNOTATION_ID_STATE_NESTED;


    // Write methods
    @android.annotation.SuppressLint("ObsoleteSdkInt")
    @RequiresApi(Build.VERSION_CODES.TIRAMISU)
    public static void write(int code, boolean arg1, int[] arg2, boolean arg3) {
        final StatsEvent.Builder builder = StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeBoolean(arg1);
        builder.writeIntArray(null == arg2 ? new int[0] : arg2);
        if (SENSITIVE_APP_LOCK_STATE_CHANGED == code) {
            builder.addBooleanAnnotation(ANNOTATION_ID_IS_UID, true);
        }
        builder.writeBoolean(arg3);

        builder.usePooledBuffer();
        StatsLog.write(builder.build());
    }

    public static void write(int code, int arg1, int arg2, int arg3, int arg4) {
        final StatsEvent.Builder builder = StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeInt(arg1);
        if (SENSITIVE_APP_LOCK_EVENT_REPORTED == code) {
            builder.addBooleanAnnotation(ANNOTATION_ID_IS_UID, true);
        }
        builder.writeInt(arg2);
        builder.writeInt(arg3);
        builder.writeInt(arg4);

        builder.usePooledBuffer();
        StatsLog.write(builder.build());
    }
}
